version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  events:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./app/.env.dev
    depends_on:
      - events-db
  events-db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=events
      - POSTGRES_PASSWORD=events
      - POSTGRES_DB=events_dev
  django-q:
    build: ./app
    command: python manage.py qcluster
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./app/.env.dev
    depends_on:
      - redis
      - events-db
volumes:
  postgres_data: